carts/urls.py
from django.urls import path
from . import views


app_name='carts'
urlpatterns = [
    path('', views.CardView.as_view(), name='home'),
  
    ]

home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    ]

shoppy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

store/urls.py
from django.urls import path
from . import views


app_name='store'
urlpatterns = [
    path('', views.StoreView.as_view(), name='home'),
    path('<slug:category_slug>/', views.StoreView.as_view(), name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password):
        if not email:
            raise ValueError('User must have an email address')

        if not username:
            raise ValueError('User must have an username')

        if not password:
            raise ValueError('User must have a password')

        user = self.model(
            email = self.normalize_email(email.lower()),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self.db)

        return user

    def create_superuser(self, first_name, last_name, username, email, password):

        if not email:
            raise ValueError('User must have an email address')

        if not username:
            raise ValueError('User must have an username')

        if not password:
            raise ValueError('User must have a password')

        user = self.create_user(
            email = self.normalize_email(email.lower()),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )

        user.is_active = True
        user.is_staff = True
        user.is_admin = True
        user.is_superadmin = True
        user.save(using=self.db)

        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    username = models.CharField(max_length=55, unique=True)
    email = models.EmailField(max_length=55, unique=True)
    phone_number = models.CharField(max_length=55)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self) -> str:
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True

    objects = MyAccountManager()

carts/models.py
from django.db import models
from store.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.cart_id} - {self.date_added}"


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.product

category/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


class Category(models.Model):
    category_name = models.CharField(max_length=55, unique=True)
    slug = models.SlugField(null=True, unique=True, blank=True)
    description = models.TextField(max_length=200, blank=True)
    cat_image = models.ImageField(upload_to='photos/categories', blank=True)
        
    def __str__(self):
        return self.category_name

    def get_url(self):
        return reverse("products_by_category", args=[self.slug])

    class Meta:
        verbose_name_plural = "categories"

home/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    price = models.FloatField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.product_name

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.category.slug, self.slug])
    

accounts/views.py
from django.shortcuts import render

# Create your views here.

carts/views.py
from django.shortcuts import render
from django.views import View


class CardView(View):
    def get(self, request):
        return render(request, "store/cart.html")

category/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render
from django.views import View
from store.models import Product

class HomeView(View):
    def get(self, request):
        product_qs = Product.objects.all().filter(is_available=True)
        context = {'products': product_qs}
        return render(request, 'home.html', context)

store/views.py
from django.shortcuts import get_object_or_404, render
from django.views import View
from .models import Product
from category.models import Category
from django.shortcuts import get_object_or_404


class StoreView(View):
    def get(self, request, category_slug=None):
        if category_slug != None:
            category_qs = Category.objects.all()
            category = get_object_or_404(Category, slug=category_slug)
            product_qs = Product.objects.filter(category=category, is_available=True)

        else:
            product_qs = Product.objects.all().filter(is_available=True)
            category_qs = Category.objects.all()
        
        context = {
            'products': product_qs,
            'categories': category_qs
        }
        return render(request, 'store/store.html', context)


class ProductDetailView(View):
    def get(self, request, category_slug, product_slug):
        product_obj = get_object_or_404(Product, slug=product_slug, category__slug=category_slug)
        context = {"product": product_obj}
        
        return render(request, 'store/product_detail.html', context)

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Shoppy | One of the Biggest Online Shopping Platform</title>

<link href='{% static "images/favicon.ico" %}' rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src='{% static "js/jquery-2.0.0.min.js" %}' type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src='{% static "js/bootstrap.bundle.min.js" %}' type="text/javascript"></script>
<link href='{% static "css/bootstrap.css" %}' rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href='{% static "fonts/fontawesome/css/all.min.css" %}' type="text/css" rel="stylesheet">

<!-- custom style -->
<link href='{% static "css/ui.css" %}' rel="stylesheet" type="text/css"/>
<link href='{% static "css/responsive.css" %}' rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src='{% static "js/script.js" %}' type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>
<body>

    {% include 'includes/navbar.html' %}

    {% block content %}
    {% endblock %}

    {% include 'includes/footer.html' %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
<div class="container">

<div class="intro-banner-wrap">
	<img src='{% static "images/banners/1.jpg" %}' class="img-fluid rounded">
</div>

</div> <!-- container //  -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
<div class="container">

<header class="section-heading">
	<a href="/store" class="btn btn-outline-primary float-right">See all</a>
	<h3 class="section-title">Popular products</h3>
</header><!-- sect-heading -->

	
<div class="row">
	{% for product in products %}
	<div class="col-md-3">
		<div class="card card-product-grid">
			<a href="{{product.get_absolute_url}}" class="img-wrap"> <img src='{{product.images.url}}'> </a>
			<figcaption class="info-wrap">
				<a href="{{product.get_absolute_url}}" class="title">{{ product.product_name }}</a>
				<div class="price mt-1">${{ product.price }}</div> <!-- price-wrap.// -->
			</figcaption>
		</div>
	</div> <!-- col.// -->
	{% endfor %}
</div> <!-- row.// -->

</div><!-- container // -->
</section>
<!-- ========================= SECTION  END// ========================= -->

</body>
</html>
{% endblock %}

templates/includes/footer.html
{% load static %}
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2019 Company name </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@pixsellz.io</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>

templates/includes/navbar.html
{% load static %}
<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTop4">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                 <a href="#" class="nav-link">   English </a>
                
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link"> USD </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
            <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
        </ul> <!-- list-inline //  -->
      </div> <!-- navbar-collapse .// -->
    </div> <!-- container //  -->
    </nav>
    
    <section class="header-main border-bottom">
        <div class="container">
    <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
            <a href="/" class="brand-wrap">
                <img class="logo" src='{% static "./images/logo.png" %}'>
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
            <div class="category-wrap dropdown d-inline-block float-right">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
                    <i class="fa fa-bars"></i> All categories 
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'store:home' %}">All Products</a>
                    {% for category in links %}
                    <a class="dropdown-item" href="/store/{{category.slug}}">{{ category.category_name }} </a>
                    {% endfor %}
                </div>
            </div>  <!-- category-wrap.// -->
        </div> <!-- col.// -->
        <a href="/store" class="btn btn-outline-primary">Store</a>
        <div class="col-lg  col-md-6 col-sm-12 col">
            <form action="#" class="search">
                <div class="input-group w-100">
                    <input type="text" class="form-control" style="width:60%;" placeholder="Search">
                    
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i>
                      </button>
                    </div>
                </div>
            </form> <!-- search-wrap .end// -->
        </div> <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        <div class="widget-header">
                            <small class="title text-muted">Welcome guest!</small>
                            <div> 
                                <a href="./signin.html">Sign in</a> <span class="dark-transp"> | </span>
                                <a href="./register.html"> Register</a>
                            </div>
                        </div>
                        <a href="./cart.html" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">0</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
    </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->
    
    
    
    
    </header> <!-- section-header.// -->

templates/store/cart.html
{% extends 'base.html' %}

{% block content %}

{%load static %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
    
    
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <div class="aside"><img src="{% static 'images/items/9.jpg' %}" class="img-sm"></div>
                <figcaption class="info">
                    <a href="#" class="title text-dark">Logitec headset for gaming</a>
                    <p class="small text-muted">Version: CUH-ZCT2E  <br> Brand: Sony</p>
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                <button class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </button>
                                </div>
                                <input type="text" class="form-control"  value="1">
                                <div class="input-group-append">
                                <button class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </button>
                                </div>
                            </div> <!-- input-group.// -->
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">$98.00</var> 
                <small class="text-muted"> $578.00 each</small> 
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
            <a href="" class="btn btn-danger"> Remove</a>
        </td>
    </tr>
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">$69.97</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> $10.00</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>$59.97</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static 'images/misc/payments.png' %}" height="26">
                </p>
                <a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
                <a href="./store.html" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>


{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap">
           <a href="{{product.images.url}}"><img src="{{product.images.url}}"></a>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">
    <article class="content-body">
    
    <h2 class="title">{{product.product_name}}</h2>
    
    <div class="mb-3"> 
        <var class="price h4">{{product.price}}</var> 
    </div> 
    
    <p>{{product.description}}</p>
    
    
    <hr>
        <div class="row">
            <div class="item-option-select">
                <h6>Choose Color</h6>
                <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color"> Silver
                  </label>
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color" > Gray
                  </label>
                  <label class="btn btn-light active">
                    <input type="radio" name="radio_color checked"> Gold
                  </label>
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color"> Black
                  </label>
                </div> 
            </div>
        </div> <!-- row.// -->
        <div class="row">
            <div class="item-option-select">
                <h6>Select Size</h6>
                <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color"> S
                  </label>
                  <label class="btn btn-light active">
                    <input type="radio" name="radio_color" checked> M
                  </label>
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color"> L
                  </label>
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color"> XL
                  </label>
                </div> 
            </div>
        </div> <!-- row.// -->
        <hr>
        {% if product.stock <= 0 %}
        <h5 class="text-danger">Out of stock</h5>
        {% else %}
        <a href="./product-detail.html" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </a>
        {% endif %}
      </article> <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3>Customer Reviews </h3>  
            
        </header>
    
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">24.04.2020 </span>  
                    <h6 class="mb-1">Mike John </h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <p>
                    Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip
                </p>	
            </div>
        </article>
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/store/store.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        <h2 class="title-page">Our Store</h2>
        
    </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->
    
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            
    <div class="card">
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Categories</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" style="">
                <div class="card-body">
                    
                    <ul class="list-menu">
                    <li><a href="{% url 'store:home' %}">All Products</a></li>
                    {% for category in categories %}
                    <li><a href="/store/{{category.slug}}">{{ category.category_name }}  </a></li>
                    {%  endfor %}
                    </ul>
    
                </div> <!-- card-body.// -->
            </div>
        </article> <!-- filter-group  .// -->
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Sizes </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_4" style="">
                <div class="card-body">
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XS </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> SM </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> LG </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XXL </span>
                  </label>
            </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Price range </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3" style="">
                <div class="card-body">
                    
                    <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Min</label>
                      <!-- <input class="form-control" placeholder="$0" type="number"> -->
                          <select class="mr-2 form-control">
                            <option value="0">$0</option>
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                        </select>
                    </div>
                    <div class="form-group text-right col-md-6">
                      <label>Max</label>
                          <select class="mr-2 form-control">
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                            <option value="2000">$2000+</option>
                        </select>
                    </div>
                    </div> <!-- form-row.// -->
                    <button class="btn btn-block btn-primary">Apply</button>
                </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <main class="col-md-9">
    
    <header class="border-bottom mb-4 pb-3">
            <div class="form-inline">
                <span class="mr-md-auto">{{products.count}} Items found </span>
                
            </div>
    </header><!-- sect-heading -->
    
    <div class="row">
        {% for  product in products %}
        <div class="col-md-4">
            <figure class="card card-product-grid">
                <div class="img-wrap">
                    <a href="{% url 'store:product_detail' product.category.slug product.slug %}" class="title">
                        <img src={{product.images.url}}>
                    </a>
                    
                    
                </div> <!-- img-wrap.// -->
                <figcaption class="info-wrap">
                    <div class="fix-height">
                        <a href="{% url 'store:product_detail' product.category.slug product.slug %}" class="title">
                            {{product.product_name}}
                        </a>
                        <div class="price-wrap mt-2">
                            <span class="price">${{product.price}}</span>
                        </div> <!-- price-wrap.// -->
                    </div>
                    {% if product.stock <= 0 %}
                    <h5 class="text-danger">Out of stock</h5>
                    {% else %}
                    <a href="#" class="btn btn-block btn-primary">Add to cart </a>	
                    {% endif %}
                </figcaption>
            </figure>
        </div> <!-- col.// -->
        {% endfor %}
    </div> <!-- row end.// -->
    
    
    <nav class="mt-4" aria-label="Page navigation sample">
      <ul class="pagination">
        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
      </ul>
    </nav>
    
        </main> <!-- col.// -->
    
    </div>
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}